"""Genre classification rules.

Each rule is (regex, tag). Rules are checked in order and the first match
wins, so more specific patterns must come before more general ones.
"""

import re

RULES = [
    # ALTERNATIVE
    (r"art punk", "Alternative//Punk//Art Punk"),
    (r"brit\s*punk", "Alternative//Punk//Britpunk"),
    (r"college rock", "Alternative//Alternative Rock//College Rock"),
    (r"crossover thrash", "Alternative//Alternative Rock//Crossover Thrash"),
    (r"crust punk", "Alternative//Punk//Crust Punk"),
    (r"emotional hardcore|emocore", "Alternative//Punk//Emotional Hardcore"),
    (r"experimental rock", "Alternative//Experimental Rock"),
    (r"folk punk", "Alternative//Punk//Folk Punk"),
    (r"goth(ic)? rock|gothic", "Alternative//Gothic Rock"),
    (r"grunge", "Alternative//Grunge"),
    (r"hardcore punk", "Alternative//Punk//Hardcore Punk"),
    (r"hard rock", "Alternative//Hard Rock"),
    (r"indie rock", "Alternative//Alternative Rock//Indie Rock"),
    (r"indie pop", "Indie Pop"),
    (r"musique concr", "Alternative//Experimental Rock//Musique Concrète"),
    (r"new wave", "Alternative//New Wave"),
    (r"progressive rock|prog rock|prog-rock", "Alternative//Progressive Rock"),
    (r"shoegaze|shoegazer", "Alternative//Shoegaze"),
    (r"steampunk", "Alternative//Steampunk"),
    # Must precede the generic \bpunk\b rule below.
    (r"pop[\s-]?punk", "Pop//Pop Punk"),
    (r"\bpunk\b", "Alternative//Punk"),
    (r"alternative rock|alt[\.\s-]?rock", "Alternative//Alternative Rock"),
    (r"lo[\s-]?fi", "Alternative//Lo-fi"),
    # BLUES
    (r"acoustic blues", "Blues//Acoustic Blues"),
    (r"african blues", "Blues//African Blues"),
    (r"blues[\s-]?rock", "Blues//Blues Rock"),
    (r"british blues", "Blues//British Blues"),
    (r"chicago blues", "Blues//Chicago Blues"),
    (r"classic female blues", "Blues//Classic Female Blues"),
    (r"contemporary blues", "Blues//Contemporary Blues"),
    (r"country blues", "Blues//Country Blues"),
    (r"delta blues", "Blues//Delta Blues"),
    (r"detroit blues", "Blues//Detroit Blues"),
    (r"electric blues", "Blues//Electric Blues"),
    (r"folk blues", "Blues//Folk Blues"),
    (r"gospel blues", "Blues//Gospel Blues"),
    (r"harmonica blues", "Blues//Harmonica Blues"),
    (r"hill country blues", "Blues//Hill Country Blues"),
    (r"jazz blues", "Blues//Jazz Blues"),
    (r"jump blues", "Blues//Jump Blues"),
    (r"kansas city blues", "Blues//Kansas City Blues"),
    (r"louisiana blues", "Blues//Louisiana Blues"),
    (r"memphis blues", "Blues//Memphis Blues"),
    (r"new orleans blues", "Blues//New Orleans Blues"),
    (r"piano blues", "Blues//Piano Blues"),
    (r"piedmont blues", "Blues//Piedmont Blues"),
    (r"punk blues", "Blues//Punk Blues"),
    (r"soul blues", "Blues//Soul Blues"),
    (r"swamp blues", "Blues//Swamp Blues"),
    (r"texas blues", "Blues//Texas Blues"),
    (r"west coast blues", "Blues//West Coast Blues"),
    (r"zydeco", "Blues//Zydeco"),
    (r"\bblues\b", "Blues"),
    # CHILDREN'S
    (r"lullab", "Children's Music//Lullabies"),
    (r"sing[\s-]?along", "Children's Music//Sing-Along"),
    (r"children|kids", "Children's Music"),
    # CLASSICAL
    (r"string quartet", "Classical//Chamber Music//String Quartet"),
    (r"chamber music", "Classical//Chamber Music"),
    (r"gregorian", "Classical//Chant//Gregorian Chant"),
    (r"\bchant\b", "Classical//Chant"),
    (r"contemporary classical", "Classical//Contemporary Classical"),
    (r"modern classical", "Classical//Modern Classical"),
    (r"\bopera\b", "Classical//Opera"),
    (r"symphon", "Classical//Symphonic"),
    (r"orchestral", "Classical//Orchestral"),
    (r"baroque", "Classical//Baroque"),
    (r"renaissance", "Classical//Renaissance"),
    (r"medieval", "Classical//Medieval"),
    (r"minimali", "Classical//Minimalism"),
    (r"twelve[\s-]?tone", "Classical//Twelve-tone"),
    (r"\bclassical\b", "Classical"),
    # COMEDY
    (r"novelty", "Comedy//Novelty"),
    (r"parody|weird al", "Comedy//Parody Music"),
    (r"stand[\s-]?up comedy", "Comedy//Stand-up Comedy"),
    (r"vaudeville", "Comedy//Vaudeville"),
    (r"\bcomedy\b", "Comedy"),
    # COUNTRY
    (r"progressive bluegrass", "Country//Bluegrass//Progressive Bluegrass"),
    (r"traditional bluegrass", "Country//Bluegrass//Traditional Bluegrass"),
    (r"contemporary bluegrass", "Country//Bluegrass//Contemporary Bluegrass"),
    (r"bluegrass", "Country//Bluegrass"),
    (r"country gospel|gospel country", "Country//Gospel Country"),
    (r"country pop|countrypolitan|nashville sound", "Country//Country Pop"),
    (r"country[\s-]?rap", "Country//Country Rap"),
    (r"country rock", "Country//Country Rock"),
    (r"country soul", "Country//Country Soul"),
    (r"honky tonk", "Country//Traditional Country//Honky Tonk"),
    (r"outlaw country", "Country//Outlaw Country"),
    (r"alternative country|alt[\s-]?country", "Country//Alternative Country"),
    (r"americana", "Country//Americana"),
    (r"red dirt", "Country//Red Dirt"),
    (r"traditional country|classic country", "Country//Traditional Country"),
    (r"\bcountry\b", "Country"),
    # DANCE / EDM
    (r"breakbeat hardcore", "Dance//Breakbeat//Breakbeat Hardcore"),
    (r"acid breaks", "Dance//Breakbeat//Acid Breaks"),
    (r"nu skool breaks", "Dance//Breakbeat//Nu Skool Breaks"),
    (r"broken beat", "Dance//Breakbeat//Broken Beat"),
    (r"big beat", "Dance//Breakbeat//Big Beat"),
    (r"\bbreakbeat\b|\bbreaks\b", "Dance//Breakbeat"),
    (r"breakcore", "Dance//Breakcore"),
    (r"brostep", "Dance//Dubstep//Brostep"),
    (r"chillstep", "Dance//Dubstep//Chillstep"),
    (r"\bdubstep\b", "Dance//Dubstep"),
    (r"acid house", "Dance//House//Acid House"),
    (r"chicago house", "Dance//House//Chicago House"),
    (r"deep house", "Dance//House//Deep House"),
    (r"electro house", "Dance//House//Electro House"),
    (r"french house", "Dance//House//French House"),
    (r"funky house", "Dance//House//Funky House"),
    (r"ghetto house", "Dance//House//Ghetto House"),
    (r"hip house", "Dance//House//Hip House"),
    (r"italo house", "Dance//House//Italo House"),
    (r"latin house", "Dance//House//Latin House"),
    (r"progressive house", "Dance//House//Progressive House"),
    (r"swing house|electro[\s-]?swing", "Dance//House//Swing House"),
    (r"tech house", "Dance//House//Tech House"),
    (r"tribal house", "Dance//House//Tribal House"),
    (r"tropical house", "Dance//House//Tropical House"),
    (r"vocal house", "Dance//House//Vocal House"),
    (r"\bhouse\b", "Dance//House"),
    (r"dark psytrance|dark psy", "Dance//Trance//Psytrance//Dark Psytrance"),
    (r"full[\s-]?on", "Dance//Trance//Psytrance//Full On"),
    (r"goa trance|goa", "Dance//Trance//Psytrance//Goa"),
    (r"psytrance|psy[\s-]?trance|psychedelic trance", "Dance//Trance//Psytrance"),
    (r"acid trance", "Dance//Trance//Acid Trance"),
    (r"dream trance", "Dance//Trance//Dream Trance"),
    (r"hard trance", "Dance//Trance//Hard Trance"),
    (r"progressive trance|prog.*trance", "Dance//Trance//Progressive Trance"),
    (r"tech trance", "Dance//Trance//Tech Trance"),
    (r"uplifting trance", "Dance//Trance//Uplifting Trance"),
    (r"vocal trance", "Dance//Trance//Vocal Trance"),
    (r"\btrance\b", "Dance//Trance"),
    (r"acid techno", "Dance//Techno//Acid Techno"),
    (r"detroit techno", "Dance//Techno//Detroit Techno"),
    (r"minimal techno", "Dance//Techno//Minimal"),
    (r"\bschranz\b", "Dance//Techno//Schranz"),
    (r"\btechno\b", "Dance//Techno"),
    (r"drum[\s&]?n[\s&]?bass|drum and bass|\bdnb\b", "Dance//Drum & Bass"),
    (r"darkstep", "Dance//Drum & Bass//Darkstep"),
    (r"liquid funk", "Dance//Drum & Bass//Liquid Funk"),
    (r"neurofunk", "Dance//Drum & Bass//Neurofunk"),
    (r"ragga jungle", "Dance//Drum & Bass//Ragga Jungle"),
    (r"\bjungle\b", "Dance//Jungle"),
    (r"gabber|gabba", "Dance//Hardcore//Gabber"),
    (r"happy hardcore", "Dance//Hardcore//Happy Hardcore"),
    (r"hardstyle", "Dance//Hardcore//Hardstyle"),
    (r"jumpstyle", "Dance//Hardcore//Jumpstyle"),
    (r"speedcore", "Dance//Hardcore//Speedcore"),
    (r"digital hardcore", "Dance//Hardcore//Digital Hardcore"),
    (r"eurodance|euro dance", "Dance//Eurodance"),
    (r"italo dance", "Dance//Eurodance//Italo Dance"),
    (r"bubblegum dance", "Dance//Eurodance//Bubblegum Dance"),
    (r"hard dance", "Dance//Hard Dance"),
    (r"hi[\s-]?nrg", "Dance//Hi-NRG"),
    (r"eurobeat", "Dance//Hi-NRG//Eurobeat"),
    (r"trip[\s-]?hop", "Dance//Downtempo//Trip Hop"),
    (r"chill[\s-]?out|chillout", "Dance//Downtempo//Chill Out"),
    (r"downtempo", "Dance//Downtempo"),
    (r"ambient dub", "Dance//Ambient//Ambient Dub"),
    (r"dark ambient", "Dance//Ambient//Dark Ambient"),
    (r"drone music|\bdrone\b", "Dance//Ambient//Drone"),
    (r"\billbient\b", "Dance//Ambient//Illbient"),
    (r"\bambient\b", "Dance//Ambient"),
    (r"chiptune|8[\s-]?bit|bitpop", "Dance//Chiptune"),
    (r"nintendocore", "Dance//Chiptune//Nintendocore"),
    (r"vaporwave", "Dance//Vaporwave"),
    (r"synthwave|retrowave", "Dance//Vaporwave//Synthwave"),
    (r"chillwave", "Dance//Vaporwave//Chillwave"),
    (r"mallsoft", "Dance//Vaporwave//Mallsoft"),
    (r"\bidm\b|intelligent dance", "Dance//IDM"),
    (r"\bglitch\b", "Dance//IDM//Glitch"),
    (r"uk garage", "Dance//UK Garage"),
    (r"2[\s-]?step", "Dance//UK Garage//2-Step"),
    (r"speed garage", "Dance//UK Garage//Speed Garage"),
    (r"\bgrime\b", "Dance//Grime"),
    (r"electropop|electro[\s-]?pop", "Dance//Electro//Electropop"),
    (r"\belectro\b", "Dance//Electro"),
    (r"folktronica", "Dance//Electronica//Folktronica"),
    (r"indietronica", "Dance//Electronica//Indietronica"),
    (r"electronica", "Dance//Electronica"),
    (r"electronic", "Dance//Electronic"),
    (r"\bedm\b", "Dance//EDM"),
    (r"\bdance\b", "Dance"),
    # EASY LISTENING
    (r"lounge", "Easy Listening//Lounge"),
    (r"elevator", "Easy Listening//Elevator"),
    (r"easy listening", "Easy Listening"),
    # FOLK
    (r"american folk revival", "Folk//American Folk Revival"),
    (r"anti[\s-]?folk", "Folk//Anti-Folk"),
    (r"british folk", "Folk//British Folk Revival"),
    (r"contemporary folk", "Folk//Contemporary Folk"),
    (r"\bfilk\b", "Folk//Filk"),
    (r"freak[\s-]?folk", "Folk//Freak Folk"),
    (r"indie folk", "Folk//Indie Folk"),
    (r"industrial folk", "Folk//Industrial Folk"),
    (r"neofolk", "Folk//Neofolk"),
    (r"progressive folk", "Folk//Progressive Folk"),
    (r"psychedelic folk|psych folk", "Folk//Psychedelic Folk"),
    (r"sea shanty", "Folk//Sea Shanty"),
    (r"\bfolk\b", "Folk"),
    # GOSPEL
    (r"southern gospel", "Gospel//Southern Gospel"),
    (r"contemporary gospel", "Gospel//Contemporary Gospel"),
    (r"\bgospel\b|\breligious\b", "Gospel"),
    # HIP HOP / RAP
    (r"alternative rap|alternative hip[\s-]?hop", "Hip-Hop//Alternative Rap"),
    (r"christian hip[\s-]?hop", "Hip-Hop//Christian Hip Hop"),
    (r"conscious hip[\s-]?hop", "Hip-Hop//Conscious Hip Hop"),
    (r"dirty south", "Hip-Hop//Dirty South"),
    (r"hardcore hip[\s-]?hop|hardcore rap", "Hip-Hop//Hardcore Rap"),
    (r"east coast hip[\s-]?hop|east coast rap", "Hip-Hop//East Coast"),
    (r"freestyle rap", "Hip-Hop//Freestyle Rap"),
    (r"g[\s-]?funk", "Hip-Hop//G-Funk"),
    (r"gangsta rap", "Hip-Hop//Gangsta Rap"),
    (r"golden age", "Hip-Hop//Golden Age"),
    (r"horrorcore", "Hip-Hop//Horrorcore"),
    (r"hyphy", "Hip-Hop//Hyphy"),
    (r"industrial hip[\s-]?hop", "Hip-Hop//Industrial Hip Hop"),
    (r"jazz rap", "Hip-Hop//Jazz Rap"),
    (r"latin rap", "Hip-Hop//Latin Rap"),
    (r"midwest hip[\s-]?hop", "Hip-Hop//Midwest Hip-Hop"),
    (r"nerdcore", "Hip-Hop//Nerdcore"),
    (r"new jack swing", "Hip-Hop//New Jack Swing"),
    (r"old school rap", "Hip-Hop//Old School Rap"),
    (r"\btrap\b", "Hip-Hop//Trap"),
    (r"turntablism", "Hip-Hop//Turntablism"),
    (r"underground rap", "Hip-Hop//Underground Rap"),
    (r"west coast rap", "Hip-Hop//West Coast Rap"),
    (r"\brap\b", "Hip-Hop//Rap"),
    (r"hip[\s-]?hop", "Hip-Hop"),
    # HOLIDAY
    (r"christmas.*jazz", "Holiday//Christmas//Jazz"),
    (r"christmas.*rock", "Holiday//Christmas//Rock"),
    (r"christmas.*pop", "Holiday//Christmas//Pop"),
    (r"christmas.*classical", "Holiday//Christmas//Classical"),
    (r"christmas", "Holiday//Christmas"),
    (r"halloween", "Holiday//Halloween"),
    (r"chanukah|hanukkah", "Holiday//Chanukah"),
    (r"\bholiday\b", "Holiday"),
    # INDUSTRIAL
    (r"aggrotech", "Industrial//Aggrotech"),
    (r"coldwave", "Industrial//Coldwave"),
    (r"dark electro", "Industrial//Dark Electro"),
    (r"death industrial", "Industrial//Death Industrial"),
    (r"electro[\s-]?industrial", "Industrial//Electro-Industrial"),
    (r"electronic body music|\bebm\b", "Industrial//Electronic Body Music"),
    (r"futurepop", "Industrial//Electronic Body Music//Futurepop"),
    (r"industrial metal", "Industrial//Industrial Metal"),
    (r"industrial rock", "Industrial//Industrial Rock"),
    (r"power electronics", "Industrial//Noise//Power Electronics"),
    (r"power noise", "Industrial//Noise//Power Noise"),
    (r"witch house", "Industrial//Witch House"),
    (r"\bnoise\b", "Industrial//Noise"),
    (r"industrial", "Industrial"),
    # INSPIRATIONAL
    (r"christian metal", "Inspirational//Christian Metal"),
    (r"christian pop", "Inspirational//Christian Pop"),
    (r"christian rap", "Inspirational//Christian Rap"),
    (r"christian rock", "Inspirational//Christian Rock"),
    (r"contemporary.*gospel|\bccm\b", "Inspirational//Contemporary Gospel"),
    (r"praise.*worship", "Inspirational//Praise & Worship"),
    (r"qawwali", "Inspirational//Qawwali"),
    (r"southern gospel", "Inspirational//Southern Gospel"),
    (r"christian", "Inspirational"),
    # JAZZ
    (r"acid jazz", "Jazz//Acid Jazz"),
    (r"afro[\s-]?cuban jazz", "Jazz//Afro-Cuban Jazz"),
    (r"avant[\s-]?garde jazz", "Jazz//Avant-Garde Jazz"),
    (r"\bbebop\b", "Jazz//Bebop"),
    (r"big band", "Jazz//Big Band"),
    (r"bossa nova", "Jazz//Bossa Nova"),
    (r"cool jazz", "Jazz//Cool Jazz"),
    (r"dark jazz", "Jazz//Dark Jazz"),
    (r"dixieland", "Jazz//Dixieland"),
    (r"free jazz", "Jazz//Free Jazz"),
    (r"fusion jazz|jazz[\s-]?fusion|jazz[\s-]?rock", "Jazz//Jazz-Fusion"),
    (r"gypsy jazz", "Jazz//Gypsy Jazz"),
    (r"hard bop", "Jazz//Hard Bop"),
    (r"jazz[\s-]?funk", "Jazz//Jazz-Funk"),
    (r"jazz[\s-]?rap", "Jazz//Jazz Rap"),
    (r"latin jazz", "Jazz//Latin Jazz"),
    (r"modal jazz", "Jazz//Modal Jazz"),
    (r"nu jazz", "Jazz//Nu Jazz"),
    (r"post[\s-]?bop", "Jazz//Post-Bop"),
    (r"ragtime", "Jazz//Ragtime"),
    (r"smooth jazz", "Jazz//Smooth Jazz"),
    (r"soul jazz", "Jazz//Soul Jazz"),
    (r"\bswing\b", "Jazz//Swing"),
    (r"vocal jazz", "Jazz//Vocal Jazz"),
    (r"west coast jazz", "Jazz//West Coast Jazz"),
    (r"\bjazz\b", "Jazz"),
    # LATIN
    (r"argentine tango", "Latin//Argentine Tango"),
    (r"bachata", "Latin//Bachata"),
    (r"bossa nova", "Latin//Bossa Nova"),
    (r"funk carioca", "Latin//Brazilian//Funk Carioca"),
    (r"música popular brasileira|\bmpb\b", "Latin//Brazilian//MPB"),
    (r"\bsamba\b", "Latin//Brazilian//Samba"),
    (r"tropicalia", "Latin//Brazilian//Tropicalia"),
    (r"\bbrazilian\b", "Latin//Brazilian"),
    (r"\bcumbia\b", "Latin//Cumbia"),
    (r"flamenco", "Latin//Flamenco"),
    (r"mariachi", "Latin//Mariachi"),
    (r"merengue", "Latin//Merengue"),
    (r"pop latino|latin pop", "Latin//Pop Latino"),
    (r"reggaeton", "Latin//Reggaeton"),
    (r"regional mexicano", "Latin//Regional Mexicano"),
    (r"\bsalsa\b", "Latin//Salsa"),
    (r"\btango\b", "Latin//Tango"),
    (r"tejano", "Latin//Tejano"),
    (r"vallenato", "Latin//Vallenato"),
    (r"\bzouk\b", "Latin//Zouk"),
    (r"\blatin\b", "Latin"),
    # METAL
    (r"blackened death", "Metal//Death Metal//Blackened Death"),
    (r"brutal death", "Metal//Death Metal//Brutal Death"),
    (r"deathcore", "Metal//Deathcore"),
    (r"melodic death", "Metal//Death Metal//Melodic Death"),
    (r"technical death|tech death", "Metal//Death Metal//Technical Death"),
    (r"progressive death", "Metal//Death Metal//Progressive Death"),
    (r"death metal", "Metal//Death Metal"),
    (r"black metal", "Metal//Black Metal"),
    (r"drone metal", "Metal//Doom Metal//Drone Metal"),
    (r"funeral doom", "Metal//Doom Metal//Funeral Doom"),
    (r"sludge metal|\bsludge\b", "Metal//Doom Metal//Sludge"),
    (r"stoner metal", "Metal//Doom Metal//Stoner Metal"),
    (r"doom metal", "Metal//Doom Metal"),
    (r"folk metal", "Metal//Folk Metal"),
    (r"glam metal|hair metal", "Metal//Glam Metal"),
    (r"gothic metal", "Metal//Gothic Metal"),
    (r"groove metal", "Metal//Heavy Metal//Groove Metal"),
    (r"heavy metal", "Metal//Heavy Metal"),
    (r"industrial metal", "Metal//Industrial Metal"),
    (r"kawaii metal", "Metal//Kawaii Metal"),
    (r"mathcore|math metal", "Metal//Mathcore"),
    (r"melodic metalcore", "Metal//Metalcore//Melodic Metalcore"),
    (r"metalcore", "Metal//Metalcore"),
    (r"neoclassical metal", "Metal//Neoclassical Metal"),
    (r"nwobhm|new wave of british heavy metal", "Metal//NWOBHM"),
    (r"nu metal", "Metal//Nu Metal"),
    (r"pagan metal", "Metal//Pagan Metal"),
    (r"post[\s-]?metal", "Metal//Post-Metal"),
    (r"post[\s-]?hardcore", "Metal//Post-Hardcore"),
    (r"power metal", "Metal//Power Metal"),
    (r"progressive metal", "Metal//Progressive Metal"),
    (r"speed metal", "Metal//Speed Metal"),
    (r"symphonic black metal", "Metal//Symphonic Metal//Symphonic Black"),
    (r"symphonic metal", "Metal//Symphonic Metal"),
    (r"crossover thrash", "Metal//Thrash Metal//Crossover Thrash"),
    (r"thrash metal", "Metal//Thrash Metal"),
    (r"viking metal", "Metal//Viking Metal"),
    (r"avant[\s-]?garde metal|avantgarde metal", "Metal//Avantgarde Metal"),
    (r"\bdjent\b", "Metal//Djent"),
    (r"grindcore", "Metal//Grindcore"),
    (r"\bmetal\b", "Metal"),
    # NEW AGE
    (r"meditation", "New Age//Meditation"),
    (r"relaxation|nature sounds", "New Age//Relaxation"),
    (r"new age", "New Age"),
    # POP
    (r"adult contemporary", "Pop//Adult Contemporary"),
    (r"britpop", "Pop//Britpop"),
    (r"bubblegum pop", "Pop//Bubblegum Pop"),
    (r"chamber pop", "Pop//Chamber Pop"),
    (r"\bchanson\b", "Pop//Chanson"),
    (r"austropop", "Pop//Europop//Austropop"),
    (r"balkan pop", "Pop//Europop//Balkan Pop"),
    (r"french pop", "Pop//Europop//French Pop"),
    (r"nederpop", "Pop//Europop//Nederpop"),
    (r"russian pop", "Pop//Europop//Russian Pop"),
    (r"europop", "Pop//Europop"),
    (r"dance[\s-]?pop", "Pop//Dance Pop"),
    (r"dream pop", "Pop//Dream Pop"),
    (r"jangle pop", "Pop//Jangle Pop"),
    (r"latin pop|pop latino", "Pop//Latin Pop"),
    (r"orchestral pop", "Pop//Orchestral Pop"),
    (r"pop rap|pop.*hip[\s-]?hop", "Pop//Pop Rap"),
    (r"pop[\s-]?rock", "Pop//Pop Rock"),
    (r"power pop", "Pop//Power Pop"),
    (r"psychedelic pop", "Pop//Psychedelic Pop"),
    (r"\bschlager\b", "Pop//Schlager"),
    (r"soft rock", "Pop//Soft Rock"),
    (r"sophisti[\s-]?pop", "Pop//Sophisti-Pop"),
    (r"sunshine pop", "Pop//Sunshine Pop"),
    (r"synthpop|synth[\s-]?pop|technopop|electropop", "Pop//Synthpop"),
    (r"teen pop", "Pop//Teen Pop"),
    (r"twee pop", "Pop//Twee Pop"),
    # Regional pop/rock (World//Asia). Must precede the generic \bpop\b and
    # \brock\b rules, which would otherwise match "K-Pop", "J-Rock", etc.
    (r"\bcantopop\b", "World//Asia//Cantopop"),
    (r"\benka\b", "World//Asia//Enka"),
    (r"\bj[\s-]?pop\b", "World//Asia//J-Pop"),
    (r"\bj[\s-]?rock\b", "World//Asia//J-Rock"),
    (r"\bk[\s-]?pop\b", "World//Asia//K-Pop"),
    (r"mandopop", "World//Asia//Mandopop"),
    (r"\bt[\s-]?pop\b", "World//Asia//T-Pop"),
    (r"kayokyoku", "World//Asia//Kayōkyoku"),
    (r"\bpop\b", "Pop"),
    # R&B / SOUL
    (r"contemporary r&b|contemporary rnb", "R&B Soul//Contemporary R&B"),
    (r"\bdisco\b", "R&B Soul//Disco"),
    (r"doo[\s-]?wop", "R&B Soul//Doo Wop"),
    (r"\bfunk\b", "R&B Soul//Funk"),
    (r"\bmotown\b", "R&B Soul//Motown"),
    (r"neo[\s-]?soul", "R&B Soul//Neo-Soul"),
    (r"northern soul", "R&B Soul//Northern Soul"),
    (r"psychedelic soul", "R&B Soul//Psychedelic Soul"),
    (r"quiet storm", "R&B Soul//Quiet Storm"),
    (r"southern soul", "R&B Soul//Southern Soul"),
    (r"\bsoul\b", "R&B Soul//Soul"),
    (r"r&b|rnb|rhythm.*blues", "R&B Soul//R&B"),
    # REGGAE
    (r"ska[\s-]?punk", "Reggae//Ska//Ska Punk"),
    (r"2[\s-]?tone|two tone", "Reggae//Ska//2 Tone"),
    (r"rocksteady", "Reggae//Ska//Rocksteady"),
    (r"\bska\b", "Reggae//Ska"),
    (r"\bdancehall\b", "Reggae//Dancehall"),
    (r"raggamuffin|\bragga\b", "Reggae//Dancehall//Ragga"),
    (r"\bdub\b", "Reggae//Dub"),
    (r"lovers rock", "Reggae//Lovers Rock"),
    (r"roots reggae", "Reggae//Roots Reggae"),
    (r"reggae fusion", "Reggae//Reggae Fusion"),
    (r"\bsurf\b", "Reggae & Surf Rock//Surf Rock"),
    (r"\breggae\b", "Reggae"),
    # ROCK
    (r"acid rock", "Rock//Psychedelic Rock//Acid Rock"),
    (r"afro[\s-]?punk", "Rock//Afro Punk"),
    (r"alternative rock|alt[\s-]?rock", "Rock//Alternative Rock"),
    (r"arena rock", "Rock//Hard Rock//Arena Rock"),
    (r"art rock", "Rock//Progressive Rock//Art Rock"),
    (r"blues[\s-]?rock", "Rock//Blues Rock"),
    (r"british invasion", "Rock//Classic Rock//British Invasion"),
    (r"classic rock", "Rock//Classic Rock"),
    (r"dance[\s-]?punk", "Rock//Post-Punk//Dance Punk"),
    (r"darkwave|dark wave", "Rock//Post-Punk//Darkwave"),
    (r"electronic rock|dance[\s-]?rock", "Rock//Electronic Rock"),
    (r"folk rock", "Rock//Folk Rock"),
    (r"funk rock", "Rock//Funk Rock"),
    (r"garage rock", "Rock//Garage Rock"),
    (r"glam rock", "Rock//Glam Rock"),
    (r"gothic rock", "Rock//Gothic Rock"),
    (r"post[\s-]?grunge", "Rock//Grunge//Post-Grunge"),
    (r"grunge", "Rock//Grunge"),
    (r"hard rock", "Rock//Hard Rock"),
    (r"indie rock", "Rock//Alternative Rock//Indie Rock"),
    (r"jam band", "Rock//Jam Band"),
    (r"math rock", "Rock//Math Rock"),
    (r"noise rock", "Rock//Experimental Rock//Noise Rock"),
    (r"post[\s-]?punk", "Rock//Post-Punk"),
    (r"post[\s-]?rock", "Rock//Post-Rock"),
    (r"progressive rock|prog rock", "Rock//Progressive Rock"),
    (r"neo[\s-]?psychedelia", "Rock//Psychedelic Rock//Neo-Psychedelia"),
    (r"space rock", "Rock//Psychedelic Rock//Space Rock"),
    (r"psychedelic rock|psych rock", "Rock//Psychedelic Rock"),
    (r"punk rock", "Rock//Punk Rock"),
    (r"rap rock", "Rock//Rap Rock"),
    (r"rock.*roll|rock and roll", "Rock//Classic Rock//Rock & Roll"),
    (r"rockabilly", "Rock//Classic Rock//Rockabilly"),
    (r"roots rock", "Rock//Classic Rock//Roots Rock"),
    (r"shoegaze|shoegazer", "Rock//Shoegaze"),
    (r"southern rock", "Rock//Southern Rock"),
    (r"stoner rock", "Rock//Stoner Rock"),
    (r"surf rock|surf music", "Rock//Surf Rock"),
    (r"yacht rock", "Rock//Soft Rock//Yacht Rock"),
    (r"\brock\b", "Rock"),
    # SINGER-SONGWRITER
    (r"alternative folk", "Singer-Songwriter//Alternative Folk"),
    (r"folk[\s-]?rock", "Singer-Songwriter//Folk-Rock"),
    (r"indie folk", "Singer-Songwriter//Indie Folk"),
    (r"singer[\s-]?songwriter", "Singer-Songwriter"),
    # SOUNDTRACK
    (r"movie soundtrack|film score", "Soundtrack//Movie Soundtrack"),
    (r"\bmusicals?\b", "Soundtrack//Musicals"),
    (r"original score", "Soundtrack//Original Score"),
    (r"tv (soundtrack|theme)", "Soundtrack//TV Soundtrack"),
    (r"\bost\b|soundtrack", "Soundtrack"),
    # SPOKEN WORD
    (r"spoken word|stand[\s-]?up", "Spoken Word"),
    # WORLD
    (r"african hip[\s-]?hop", "World//Africa//African Hip Hop"),
    (r"afro[\s-]?beat", "World//Africa//Afro-Beat"),
    (r"afro[\s-]?house", "World//Africa//Afro-House"),
    (r"afro[\s-]?pop", "World//Africa//Afro-Pop"),
    (r"highlife", "World//Africa//Highlife"),
    (r"hiplife", "World//Africa//Hiplife"),
    (r"kwaito", "World//Africa//Kwaito"),
    (r"makossa", "World//Africa//Makossa"),
    (r"soukous", "World//Africa//Soukous"),
    (r"\bcalypso\b", "World//Caribbean//Calypso"),
    (r"\bcompas\b", "World//Caribbean//Compas"),
    (r"\bsoca\b", "World//Caribbean//Soca"),
    (r"caribbean", "World//Caribbean"),
    (r"\bcajun\b", "World//Cajun"),
    (r"\bceltic\b", "World//Celtic"),
    (r"\bklezmer\b", "World//Klezmer"),
    (r"\bpolka\b", "World//Polka"),
    (r"\bfado\b", "World//Europe//Fado"),
    (r"bhangra", "World//South Asia//Bhangra"),
    (r"dangdut", "World//Southeast Asia//Dangdut"),
    (r"hindustani", "World//South Asia//Hindustani"),
    (r"worldbeat|world fusion", "World//Worldbeat"),
    (r"\bworld\b", "World"),
]

def classify_genre(genre: str) -> str:
    g = genre.strip().lower()
    if not g:
        return "Other"
    for pattern, tag in RULES:
        if re.search(pattern, g, re.IGNORECASE):
            return tag
    return "Other"
